name: Remote Command Trigger
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command'
        required: true
        default: 'RUN'
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name "Mind-Xai Robot"
          git config user.email "mindxxx333@gmail.com"
          echo "${{ inputs.command }}" > command.txt
          
          # Sirf tab commit karo agar change hua ho
          if [[ -n $(git status -s) ]]; then
            git add command.txt
            git commit -m "Remote Update: ${{ inputs.command }}"
            git push
          else
            echo " No changes needed (Already set)"
          fi
